FROM node:alpine AS build
WORKDIR /app
COPY ./ ./
RUN npi ci
RUN npm build

FROM node:alpine AS run
WORKDIR ./app
COPY --from=build ./app/package*.json ./
COPY --from=build ./app/.next ./
# move the current directory once level higher than the project in the app folder 
#(a hack to work around the mounting of the source file "I quoted directly from google").

# Install all node packages (dependancies)
RUN npm ci
ENTRYPOINT ["npm", "run", "start"] 
#WORKDIR /App/app

# Expose PORT on container.
EXPOSE 3000

# Start the app