name: Build and Deploy Client

defaults:
  run:
    working-directory: src/Web/client

on:
  push:
    branches: [main]
    paths: [src/Web/client/**]
  pull_request:
    branches: [main]
    paths: [src/Web/client/**]

  workflow_dispatch:

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
      #TODO: Add tests
    - name: Run tests
      run: echo "no tests to run"
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ vars.DOCKER_HUB_REPO }}/${{ vars.CLIENT_IMAGE_NAME }}
        tags: ${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        #TODO: Change to prod Dockerfile
        dockerfile: src/Web/client/Dockerfile-run-dev
