name: Build and Deploy API

on:
  push:
    branches: [workflow]
    paths-ignore: [src/Web/client/**]
  pull_request:    
    branches: [workflow]
    paths-ignore: [src/Web/client/**]

  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies and tools
      run: dotnet restore
    - name: Build project
      run: dotnet build
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ vars.DOCKER_HUB_REPO }}/${{ vars.API_IMAGE_NAME }}
        tags: mygamestat-backend${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: src/Web/API/Dockerfile
        
        
  deploy:
    # Specify which job needs to be finished first
    
    runs-on: ubuntu-latest

    steps:
      # Check the system
      - name: deploy-sanity-check
        run: echo "Keep deploying"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mygamestat-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} #checks azure publish
          images: 'index.docker.io/ommarico2/mygamestat-backend:v1${{ github.sha }}'
      
    