name: API Build and Deploy

#triggers
on:
  push:
  #conditions
    branches: # Specify the branch that needs deployment (checkup)
      - workflow

    # Specify the folder that trigger build and deployment on changes   
  pull_request:    
    branches:
      - workflow 
  workflow_dispatch: # allow action to run

# tasks to complete (actual pipeline creation)
jobs:
  #each job will run on a new vm(build agent)
  build:
    runs-on: ubuntu-latest #what type of vm will this job be performed on

    #what steps we take to complete the job
    steps:
      # We tell the VM the source code
    - name: Checkout The Repo
      uses: actions/checkout@v4

    - name: Setup .NET #instruction to tell the VM will be based on .NET version 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

     #install dependancies 
    - name: Dotnet Restore
      run: dotnet restore ./src/Web/API/

      #start building .net project
    - name: Dotnet Build
      run: dotnet build ./src/Web/API/ --no-restore
    
    